config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'
    
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    resources :projects, only: [] do
      resources :tickets
    end
  end

  devise_for :users

  
  root "projects#index"
  resources :projects, only: [:index, :update, :edit, :show] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end
  
  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
  
  resources :attachments, only: [:show, :new]
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def remove
    @ticket = Ticket.find(params[:ticket_id])
    @tag = Tag.find(params[:id])
    authorize @ticket, :tag?

    @ticket.tags.destroy(@tag)
    head :ok
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= f.input :tag_names, label: "Tags" %>

app/views/tags/_tag.html.erb
<div class="tag">
  <% if policy(ticket).tag? %>
    <%= link_to "<span></span>".html_safe, remove_ticket_tag_path(ticket, tag), method: :delete, remote: true, class: "remove", title: "remove" %>
  <% end %>
  <%= link_to tag.name, search_project_tickets_path(ticket.project, search: "tag:#{tag.name}") %>
</div>